global MAX_LEVELS;
MAX_LEVELS = 100
global START_MRESISTANCE;
START_MRESISTANCE = 3
global START_HP;
START_HP = 50
global START_AD;
START_AD = 10
global START_AP;
START_AP = 7
global START_BRESISTANCE;
START_BRESISTANCE = 1